"use client";

import { useState } from "react";
import { toast } from "sonner";
import { Loader2, QrCode, ScanLine } from "lucide-react";

import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import {
  QR_PREFILLED_MESSAGE_MAX_LENGTH,
  type QrImageFormat,
} from "@/lib/whatsapp/meta-api";
import { QR_NAME_MAX_LENGTH } from "@/lib/qr-codes/types";

/**
 * Create dialog. The name is WACRM-local (Meta has no name field);
 * the QR itself is generated by Meta on submit.
 */
export function CreateQrDialog({
  open,
  onOpenChange,
  onCreated,
}: {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  onCreated: () => void;
}) {
  const [name, setName] = useState("");
  const [message, setMessage] = useState("");
  const [format, setFormat] = useState<QrImageFormat>("SVG");
  const [saving, setSaving] = useState(false);

  const nameValid = name.trim().length > 0 && name.trim().length <= QR_NAME_MAX_LENGTH;
  const messageValid =
    message.trim().length > 0 &&
    message.trim().length <= QR_PREFILLED_MESSAGE_MAX_LENGTH;
  const canSubmit = nameValid && messageValid && !saving;

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    if (!canSubmit) return;
    setSaving(true);
    try {
      const res = await fetch("/api/qr-codes", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          name: name.trim(),
          prefilled_message: message.trim(),
          image_format: format,
        }),
      });
      const json = (await res.json().catch(() => null)) as {
        error?: string;
      } | null;
      if (!res.ok) throw new Error(json?.error ?? "Could not create the QR code.");
      toast.success("QR code created in WhatsApp.");
      setName("");
      setMessage("");
      setFormat("SVG");
      onOpenChange(false);
      onCreated();
    } catch (error) {
      toast.error(error instanceof Error ? error.message : "Could not create the QR code.");
    } finally {
      setSaving(false);
    }
  }

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-md">
        <DialogHeader>
          <DialogTitle>Create WhatsApp QR code</DialogTitle>
          <DialogDescription>
            The QR code is generated by WhatsApp. The name is only used
            inside WACRM to organize your codes.
          </DialogDescription>
        </DialogHeader>
        <form onSubmit={handleSubmit} className="grid gap-4">
          <div className="grid gap-2">
            <Label htmlFor="qr-name">Name</Label>
            <Input
              id="qr-name"
              value={name}
              onChange={(e) => setName(e.target.value)}
              placeholder="e.g. Bali Packages"
              maxLength={QR_NAME_MAX_LENGTH + 10}
              autoComplete="off"
            />
          </div>
          <div className="grid gap-2">
            <div className="flex items-baseline justify-between">
              <Label htmlFor="qr-message">Prefilled message</Label>
              <span className="text-xs text-muted-foreground">
                {message.trim().length}/{QR_PREFILLED_MESSAGE_MAX_LENGTH}
              </span>
            </div>
            <Textarea
              id="qr-message"
              value={message}
              onChange={(e) => setMessage(e.target.value)}
              placeholder="e.g. Hi, I want to know about your Bali packages."
              rows={3}
            />
            <p className="text-xs text-muted-foreground">
              This message appears pre-filled when a customer opens the chat.
            </p>
          </div>
          <div className="grid gap-2">
            <Label htmlFor="qr-format">QR image format</Label>
            <div className="flex gap-2" role="radiogroup" aria-label="QR image format">
              {(["SVG", "PNG"] as const).map((f) => (
                <button
                  key={f}
                  type="button"
                  role="radio"
                  aria-checked={format === f}
                  onClick={() => setFormat(f)}
                  className={
                    format === f
                      ? "flex-1 rounded-lg border border-primary bg-primary-soft px-3 py-2 text-sm font-medium text-primary"
                      : "flex-1 rounded-lg border border-border bg-background px-3 py-2 text-sm font-medium text-muted-foreground hover:text-foreground"
                  }
                >
                  {f}
                </button>
              ))}
            </div>
          </div>
          {/* Customer-experience preview — static, educational. */}
          <div className="rounded-lg border border-border bg-muted/50 p-3">
            <p className="flex items-center gap-1.5 text-xs font-medium text-foreground">
              <ScanLine className="h-3.5 w-3.5 text-primary" />
              What the customer experiences
            </p>
            <ol className="mt-2 space-y-1 text-xs text-muted-foreground">
              {[
                "Customer scans the QR",
                "WhatsApp opens with your message pre-filled",
                "Customer taps send — the chat enters your WACRM inbox",
              ].map((step, i) => (
                <li key={step} className="flex gap-2">
                  <span className="flex h-4 w-4 shrink-0 items-center justify-center rounded-full bg-primary-soft text-[10px] font-semibold text-primary">
                    {i + 1}
                  </span>
                  {step}
                </li>
              ))}
            </ol>
          </div>
          <DialogFooter>
            <Button type="button" variant="outline" onClick={() => onOpenChange(false)}>
              Cancel
            </Button>
            <Button type="submit" disabled={!canSubmit}>
              {saving ? (
                <>
                  <Loader2 className="h-4 w-4 animate-spin" />
                  Creating in WhatsApp…
                </>
              ) : (
                <>
                  <QrCode className="h-4 w-4" />
                  Create QR code
                </>
              )}
            </Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  );
}
